server:
  port: 8888

spring:
  application:
    name: gateway

  cloud:
    nacos:
      discovery:
        server-addr: 192.168.253.128:8848

    gateway:
      routes:
        - id: public_main
          uri: lb://main
          predicates:
            - Path=/public/main/**
          filters:
            - StripPrefix=2

        - id: main
          uri: lb://main
          predicates:
            - Path=/main/**
          filters:
            - StripPrefix=1